chore: Update CI pipelines to hardened resources
cloud-gov/pages-proxy pull request #202
Opened 2024-02-14 15:56 UTC by apburnes

Closes https://github.com/cloud-gov/pages-proxy/issues/201

## Changes proposed in this pull request:
- Update Node to v20 and audit fix deps
- Use hardened resource types in CI

## security considerations
Updates to Node v20 with hardened image resources=

2024-02-14 22:49 UTC, svenaas requested changes
The pipeline/resource changes look good to me. I noticed a typo that could potentially be fixed while you're in there.

2024-02-14 22:49 UTC, svenaas commented on README.md
>  The pipeline and each of it's instances will only need to be set once per instance to create the initial pipeline. After the pipelines are set, updates to the respective `git-branch` source will auto
This isn't new, but I just noticed it:
```suggestion
The pipeline and each of its instances will only need to be set once per instance to create the initial pipeline. After the pipelines are set, updates to the respective `git-branch` source will automatically set the pipeline with any updates. See the [`set_pipeline` step](https://concourse-ci.org/set-pipeline-step.html) for more information. Run the following command with the fly CLI to set a pipeline instance:
```

2024-02-14 23:04 UTC, svenaas approved these changes
Looks good to me!

2024-02-15 00:21 UTC, drewbo approved these changes

2024-02-15 14:50 UTC, merged